name: CI
on:
  push:
    branches:
      - 'main'
      - 'versions/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci --ignore-scripts --legacy-peer-deps
      - run: npm run lint
  test-unit:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
        node-version:
          - '14.x'
          - '16.0'
          - '16.x'
          - '18.0'
          - '18.x'
    timeout-minutes: 15
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies and run build scripts
        run: npm ci --legacy-peer-deps
      - name: Type-check tests
        run: npm run test:ts
      - name: Run unit tests
        run: npm run test:unit
      - name: Submit unit test coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: test-unit-${{ matrix.node-version }}-${{ matrix.operating-system }}
          parallel: true
  test-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16.x'
          - '18.x'
    env:
      TEST_DOCKER: true
      TICKETMASTER_APIKEY: ${{ secrets.TICKETMASTER_APIKEY }}
    services:
      blazegraph:
        image: nawer/blazegraph:2.1.5
        ports:
          - 9999:9999
    timeout-minutes: 15
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies and run build scripts
        run: npm ci --legacy-peer-deps
      - name: Run integration tests
        run: npm run test:integration
  test-integration-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version:
          - '16.x'
          - '18.x'
    timeout-minutes: 15
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies and run build scripts
        run: npm ci --legacy-peer-deps
      - name: Run integration tests
        run: npm run test:integration
  test-package:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-12
    env:
      TICKETMASTER_APIKEY: ${{ secrets.TICKETMASTER_APIKEY }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies and run build scripts
        run: npm ci --legacy-peer-deps
      - name: Run package tests
        run: npm run test:package
  coveralls:
    needs: test-unit
    runs-on: ubuntu-latest
    steps:
      - name: Consolidate test coverage from different jobs
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
